### ISSUE TITLE
v5

### ISSUE THREAD

**Issue by josephzidell** [spatie/laravel-blade#2]
This package could seriously help large projects from other MVC frameworks migrate to Laravel. Any plans to make this work with latest blade v5?

**Comment by freekmurze** [comment]
Nope, we created this package we were transitioning to Laravel. All apps we made in the past 3 or 4 years are Laravel apps, so we don't need this bridge anymore.

Take a look at @mattstauffer 's [Torch repo](https://github.com/mattstauffer/Torch) to Learn how to use Laravel 5 components in legacy apps.
